console.log(100);
console.log('Xin chào');
console.log(20, 'Xin chào', true);
const x = 100;
console.log(x);
console.error('Xin chào');
console.warn('Xin chào');
console.table({ tên: 'Brad', email: 'brad@gmail.com' });
console.group('Đơn giản');
console.log(x);
console.error('Xin chào');
console.warn('Xin chào');
console.groupEnd();
const styles = 'padding: 10px; background-color: white; color: green';
console.log('%cXin chào', styles);
